#:schema node_modules/wrangler/config-schema.json
name = "punch-in"
main = "src/index.ts"
compatibility_date = "2024-07-22"
node_compat = true

[triggers]
crons = []

[[d1_databases]]
binding = "DB"
database_name = "punch-in-sit"
database_id = "b6ac5b50-d517-4a50-b264-bbdf1897daf5"
preview_database_id = "b6ac5b50-d517-4a50-b264-bbdf1897daf5"

[[kv_namespaces]]
binding = "KV"
id = "e7c4697d2e5142129b61b051c8cf6116"
preview_id = "e7c4697d2e5142129b61b051c8cf6116"
