#:schema node_modules/wrangler/config-schema.json
name = "workerrr"
main = "src/index.ts"
compatibility_date = "2024-07-22"
node_compat = true

[triggers]
crons = ["0 7 * * *", "5 7 * * *", "10 7 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "workerrr"
database_id = "c07c1bb8-452f-4fd6-b1de-ba1e0b61c49d"
preview_database_id = "c07c1bb8-452f-4fd6-b1de-ba1e0b61c49d"

[[kv_namespaces]]
binding = "KV"
id = "c151c4fb241241b58b4806b7a12f68e2"
preview_id = "c151c4fb241241b58b4806b7a12f68e2"
